// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CratedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("SeoAuthor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SeoTag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Articles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 11,
                            CommentCount = 60,
                            Content = "İllum omnis autem officia molestiae. Veniam consequatur consequatur. Dolore iusto neque nihil reiciendis magni hic et accusantium id.\n\nUt architecto nemo eaque laudantium molestiae. Et cum iusto temporibus deserunt. Tempora eum cupiditate iusto rem ullam dolores. İn ex aliquam.\n\nQuaerat minima aut temporibus aut explicabo aut perspiciatis. Quos voluptates inventore aut earum sit. Sunt dolores corporis ad dolorum.",
                            CratedDate = new DateTime(2024, 6, 10, 3, 19, 0, 332, DateTimeKind.Local).AddTicks(9828),
                            CreatedByName = "Nils O'Reilly",
                            Date = new DateTime(2024, 1, 24, 7, 32, 15, 360, DateTimeKind.Local).AddTicks(4686),
                            IsActive = false,
                            IsDeleted = true,
                            ModifiedByName = "Alden Moen",
                            ModifiedDate = new DateTime(2024, 11, 25, 15, 33, 6, 146, DateTimeKind.Local).AddTicks(6561),
                            Note = "Eos et in id totam.",
                            SeoAuthor = "Rosalyn Parker",
                            SeoDescription = "At accusantium aut vel laborum et et error nam incidunt.",
                            SeoTag = "suscipit",
                            Thumbnail = "https://picsum.photos/640/480/?image=21",
                            Title = "Et labore explicabo minima odio.",
                            UserId = 6,
                            ViewsCount = 1676
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 4,
                            CommentCount = 89,
                            Content = "İusto dolore dolor nam reprehenderit adipisci. Fugiat aut accusantium. Quos non cumque blanditiis molestiae odio voluptatem.\n\nQui vitae culpa est deserunt. Repellat dicta nesciunt magnam vel possimus rerum. Sit repudiandae voluptas officiis laborum. Eaque libero amet qui voluptatum quis. Ut consequatur veniam. Praesentium quisquam aliquid dicta ratione facilis in assumenda dolor.\n\nFacilis quos rem esse autem quibusdam assumenda itaque qui voluptas. Fuga repellat ut explicabo quo officia maiores quis minima ut. Sunt suscipit voluptatem in dolores quia ipsum. Eos dolor culpa dolore et.",
                            CratedDate = new DateTime(2024, 5, 12, 18, 48, 23, 315, DateTimeKind.Local).AddTicks(4502),
                            CreatedByName = "Jovani Greenfelder",
                            Date = new DateTime(2024, 8, 6, 20, 42, 24, 866, DateTimeKind.Local).AddTicks(6850),
                            IsActive = true,
                            IsDeleted = true,
                            ModifiedByName = "Ashlee Lebsack",
                            ModifiedDate = new DateTime(2024, 11, 25, 1, 47, 35, 385, DateTimeKind.Local).AddTicks(9733),
                            Note = "Et assumenda ut id tenetur.",
                            SeoAuthor = "Stephon Keeling",
                            SeoDescription = "Dolores perspiciatis nesciunt totam similique non dolorum ipsa aliquid veritatis.",
                            SeoTag = "eum",
                            Thumbnail = "https://picsum.photos/640/480/?image=939",
                            Title = "Velit sapiente tempora atque nemo.",
                            UserId = 20,
                            ViewsCount = 2788
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CommentCount = 92,
                            Content = "Minus et ut repudiandae corporis quas quam. Quidem culpa cumque et vitae cum impedit eaque quod corporis. Mollitia quos fugit et in sunt. Velit nemo dolorem ea.\n\nEveniet qui est rerum omnis. Nesciunt voluptas distinctio ut veniam possimus. At ex natus voluptas voluptatum consequatur voluptatibus numquam illum. Aut earum ea reprehenderit consequuntur dolorem sit officia qui asperiores. Maxime minima eligendi odit.\n\nMinus et et eos numquam sit non perspiciatis ut. Sapiente quam et necessitatibus omnis tempora eos et. Dicta delectus illo aut est. Quis officia dolores hic et. Assumenda illo nam fugit molestiae et eaque quasi ut. Blanditiis optio officia quia omnis quia.",
                            CratedDate = new DateTime(2024, 3, 22, 2, 36, 5, 472, DateTimeKind.Local).AddTicks(1477),
                            CreatedByName = "Miller Quigley",
                            Date = new DateTime(2024, 6, 19, 5, 52, 36, 948, DateTimeKind.Local).AddTicks(3428),
                            IsActive = false,
                            IsDeleted = true,
                            ModifiedByName = "April Quitzon",
                            ModifiedDate = new DateTime(2024, 11, 25, 1, 21, 44, 446, DateTimeKind.Local).AddTicks(4353),
                            Note = "Quam fugiat omnis dolor quia.",
                            SeoAuthor = "Kim Rodriguez",
                            SeoDescription = "Reprehenderit et molestias voluptate ut nihil tempore aspernatur sit excepturi.",
                            SeoTag = "veniam",
                            Thumbnail = "https://picsum.photos/640/480/?image=88",
                            Title = "Aut ut consequatur distinctio quibusdam.",
                            UserId = 7,
                            ViewsCount = 1643
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 14,
                            CommentCount = 79,
                            Content = "Atque dolorem excepturi numquam deserunt ipsa et qui. İn a qui et. Ea error dolor enim natus laudantium labore autem. Ad et quisquam tempore earum pariatur porro ipsam. Qui voluptas autem ut. Et itaque voluptatem.\n\nMolestias vel a similique laborum alias quos repellendus eaque beatae. Qui corporis veniam et debitis placeat. Rerum et iste enim officiis. Non ipsum quia et. Assumenda laudantium qui quo quisquam.\n\nLaboriosam quia est voluptates ipsam nemo ad. Nemo et minima omnis numquam odit vel quia provident enim. Neque debitis ad corrupti molestiae non id. Ut sit deleniti.",
                            CratedDate = new DateTime(2024, 6, 25, 9, 32, 56, 315, DateTimeKind.Local).AddTicks(9804),
                            CreatedByName = "Nathanial Kulas",
                            Date = new DateTime(2024, 2, 28, 2, 27, 3, 20, DateTimeKind.Local).AddTicks(7298),
                            IsActive = false,
                            IsDeleted = true,
                            ModifiedByName = "Carrie Beer",
                            ModifiedDate = new DateTime(2024, 11, 25, 5, 59, 2, 46, DateTimeKind.Local).AddTicks(1806),
                            Note = "Molestiae dolorem sed veniam et.",
                            SeoAuthor = "Griffin Christiansen",
                            SeoDescription = "Et praesentium reiciendis optio quasi similique et dolorum voluptates sapiente.",
                            SeoTag = "rerum",
                            Thumbnail = "https://picsum.photos/640/480/?image=334",
                            Title = "Mollitia et beatae aspernatur dolorem.",
                            UserId = 20,
                            ViewsCount = 4307
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 12,
                            CommentCount = 83,
                            Content = "Odio sapiente laborum est ipsum labore. Dolor cupiditate voluptas adipisci. Ab voluptatibus iure labore quo corrupti. Nemo expedita dolor occaecati mollitia similique perferendis. Similique enim in iure sed sequi assumenda. İtaque voluptatibus voluptates fugiat.\n\nFugiat rerum doloremque. Provident consectetur eos sed molestias harum harum numquam natus. Laboriosam non nostrum corporis ad consequatur inventore odit. Adipisci tenetur incidunt in temporibus quo voluptas ad officiis. Voluptatem debitis sint laborum cupiditate molestiae quia autem.\n\nNecessitatibus in aut. Totam minima et laboriosam accusamus. Et at expedita. Qui culpa possimus inventore sint dolor ullam qui. Odio odio quia ullam. Atque fugiat nisi corrupti animi alias recusandae nulla id.",
                            CratedDate = new DateTime(2024, 4, 28, 18, 41, 47, 966, DateTimeKind.Local).AddTicks(5216),
                            CreatedByName = "Clint Cruickshank",
                            Date = new DateTime(2024, 1, 28, 1, 24, 26, 2, DateTimeKind.Local).AddTicks(4299),
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Bret Stoltenberg",
                            ModifiedDate = new DateTime(2024, 11, 25, 8, 23, 35, 150, DateTimeKind.Local).AddTicks(8771),
                            Note = "Labore occaecati qui iste voluptas.",
                            SeoAuthor = "Ethelyn Klein",
                            SeoDescription = "Dolor nostrum est est enim corrupti quis optio nihil iusto.",
                            SeoTag = "ea",
                            Thumbnail = "https://picsum.photos/640/480/?image=31",
                            Title = "Quisquam soluta vel incidunt non.",
                            UserId = 3,
                            ViewsCount = 5406
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 9,
                            CommentCount = 71,
                            Content = "Molestiae perferendis et illo assumenda dolor amet autem omnis quia. İllo dolore voluptate rerum voluptatibus nobis sunt libero veritatis repellat. Nobis odit recusandae sed aliquam est quia et debitis. Tempore sit eius dolore similique est voluptatem qui. Necessitatibus cum pariatur. Aut totam molestiae sequi mollitia mollitia.\n\nUt adipisci praesentium saepe et consequatur. Dicta voluptate ut quia sequi quos. Officiis in sunt magnam magnam praesentium modi aut natus. Quas accusantium assumenda. İure totam ipsa. İd quae quae magnam ut voluptatum.\n\nEst autem quae libero architecto aut fugit quas. Et vero quia voluptatem sit sapiente et. Cumque inventore quaerat repudiandae quia repudiandae. Soluta iusto molestiae id voluptatem reiciendis. Maiores consequatur recusandae molestiae.",
                            CratedDate = new DateTime(2024, 4, 25, 9, 35, 55, 985, DateTimeKind.Local).AddTicks(7563),
                            CreatedByName = "Delta Gorczany",
                            Date = new DateTime(2024, 10, 22, 7, 34, 46, 769, DateTimeKind.Local).AddTicks(3680),
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Sabrina Miller",
                            ModifiedDate = new DateTime(2024, 11, 25, 9, 18, 49, 349, DateTimeKind.Local).AddTicks(419),
                            Note = "Blanditiis nisi earum aut itaque.",
                            SeoAuthor = "Joel Stokes",
                            SeoDescription = "Quam reprehenderit omnis aspernatur nam voluptatem vel aut quas et.",
                            SeoTag = "natus",
                            Thumbnail = "https://picsum.photos/640/480/?image=71",
                            Title = "Suscipit odit aut est perspiciatis.",
                            UserId = 7,
                            ViewsCount = 3334
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 11,
                            CommentCount = 89,
                            Content = "Nihil placeat magnam odio nemo. Accusantium ipsam molestiae sed quas. Voluptate quae libero earum iste. Reiciendis delectus voluptate laudantium.\n\nMinima alias debitis praesentium vitae voluptas eum. Similique omnis esse dolor quae. Eius quis non dolores eos non unde nemo magni. Quam voluptas neque consequuntur.\n\nTenetur labore assumenda. Dolor consequatur ut sed facere consequuntur. Tempora a occaecati possimus laborum similique nesciunt. İpsum cupiditate tenetur enim autem.",
                            CratedDate = new DateTime(2024, 11, 12, 3, 43, 37, 53, DateTimeKind.Local).AddTicks(2831),
                            CreatedByName = "Santa Kertzmann",
                            Date = new DateTime(2024, 1, 30, 21, 11, 40, 339, DateTimeKind.Local).AddTicks(7295),
                            IsActive = true,
                            IsDeleted = true,
                            ModifiedByName = "Fatima Klocko",
                            ModifiedDate = new DateTime(2024, 11, 25, 15, 25, 34, 615, DateTimeKind.Local).AddTicks(2924),
                            Note = "Modi debitis ut voluptate nesciunt.",
                            SeoAuthor = "Franco Reilly",
                            SeoDescription = "Sit beatae officiis vitae et consequuntur repudiandae numquam accusantium occaecati.",
                            SeoTag = "sit",
                            Thumbnail = "https://picsum.photos/640/480/?image=1050",
                            Title = "Rerum ut est veniam vitae.",
                            UserId = 14,
                            ViewsCount = 597
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 13,
                            CommentCount = 27,
                            Content = "Aut fuga libero perferendis in nulla ut. Architecto facere sunt ea at. Ut ut ut.\n\nEt rem aut fuga rerum itaque rem explicabo ab et. Repellat sit atque accusamus. Culpa similique quos.\n\nRerum molestiae praesentium at provident non architecto quia accusamus quis. Nostrum facilis aut sit quia facilis ut explicabo aut animi. Consectetur nulla enim fugit expedita id. Odit fugiat totam aut nostrum. İn voluptate et veritatis adipisci.",
                            CratedDate = new DateTime(2024, 8, 8, 9, 31, 15, 487, DateTimeKind.Local).AddTicks(1612),
                            CreatedByName = "Florian Stamm",
                            Date = new DateTime(2024, 4, 23, 13, 11, 11, 463, DateTimeKind.Local).AddTicks(1218),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "Judson Blick",
                            ModifiedDate = new DateTime(2024, 11, 25, 20, 22, 51, 626, DateTimeKind.Local).AddTicks(3511),
                            Note = "Nostrum rerum non ducimus sit.",
                            SeoAuthor = "Kacey Hahn",
                            SeoDescription = "Tempore quibusdam eaque perferendis provident veniam minus incidunt laborum id.",
                            SeoTag = "voluptatem",
                            Thumbnail = "https://picsum.photos/640/480/?image=709",
                            Title = "Beatae omnis voluptatibus voluptatem id.",
                            UserId = 17,
                            ViewsCount = 8182
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CommentCount = 76,
                            Content = "Rerum suscipit earum odit dolore corporis non cumque. Maiores et praesentium omnis atque. Saepe corporis vel. Quo voluptatum magnam aliquam unde sapiente. Officiis et rem earum maxime. Esse quas neque nostrum.\n\nAccusamus nostrum distinctio voluptates distinctio architecto quaerat. Nam error sequi odio quae laudantium repellat quia omnis consequatur. Modi aut dolorem rerum sapiente voluptatem. Sit sit aut suscipit veniam. Est voluptatem sequi tempora eos ut excepturi.\n\nEt nostrum adipisci et molestiae. İpsum vero tenetur qui aut. Quia rerum voluptas quam aut suscipit magni tempora accusantium. İnventore fugit quisquam recusandae quaerat error sit. İnventore repudiandae cumque dolores error repudiandae temporibus. Eligendi accusantium error fugiat delectus laborum ipsa et.",
                            CratedDate = new DateTime(2024, 4, 8, 0, 15, 8, 237, DateTimeKind.Local).AddTicks(305),
                            CreatedByName = "Joyce Koelpin",
                            Date = new DateTime(2024, 10, 26, 4, 36, 27, 840, DateTimeKind.Local).AddTicks(1791),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "Estevan Kub",
                            ModifiedDate = new DateTime(2024, 11, 25, 1, 7, 31, 63, DateTimeKind.Local).AddTicks(5517),
                            Note = "Minus ducimus eius nam consequatur.",
                            SeoAuthor = "Woodrow Zulauf",
                            SeoDescription = "Eligendi natus ut pariatur labore sint expedita perferendis nihil ut.",
                            SeoTag = "asperiores",
                            Thumbnail = "https://picsum.photos/640/480/?image=834",
                            Title = "Quia sit vel odio et.",
                            UserId = 12,
                            ViewsCount = 5995
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CommentCount = 81,
                            Content = "İd quia saepe non autem fugiat. At et facere exercitationem exercitationem alias in deleniti minus consequatur. Voluptate quia animi aliquam saepe aut.\n\nAccusamus in est a sit dolorum id alias officia. Vitae eaque et. Porro excepturi quia ipsum cum magnam cupiditate amet perferendis molestias. Tenetur sit beatae ut qui est. Est quia voluptatibus corrupti corporis aspernatur. Autem ipsam possimus velit maiores quia porro animi.\n\nAdipisci sed qui fugit unde qui saepe. Aliquid nulla quis consectetur debitis quos aperiam vero. At est voluptatem ullam facilis officia sed expedita libero. Quod accusantium illum aspernatur consequatur. Doloremque ut autem inventore sunt porro impedit corrupti.",
                            CratedDate = new DateTime(2024, 8, 30, 7, 57, 53, 140, DateTimeKind.Local).AddTicks(30),
                            CreatedByName = "Trevion Maggio",
                            Date = new DateTime(2024, 2, 19, 23, 28, 2, 286, DateTimeKind.Local).AddTicks(2741),
                            IsActive = false,
                            IsDeleted = true,
                            ModifiedByName = "Jaydon Langosh",
                            ModifiedDate = new DateTime(2024, 11, 25, 9, 10, 22, 865, DateTimeKind.Local).AddTicks(8319),
                            Note = "Veritatis delectus quas vitae dicta.",
                            SeoAuthor = "Vance Lehner",
                            SeoDescription = "Et officia corrupti debitis laboriosam molestiae est voluptatum iste veritatis.",
                            SeoTag = "cum",
                            Thumbnail = "https://picsum.photos/640/480/?image=941",
                            Title = "Consequuntur quo nostrum qui reprehenderit.",
                            UserId = 19,
                            ViewsCount = 2430
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 7,
                            CommentCount = 15,
                            Content = "Autem asperiores sit quo distinctio facilis modi non asperiores. Quam deleniti dolores nam quia. Nam reiciendis et voluptatem iure voluptas quas. İure porro vel doloremque perspiciatis ut velit culpa. Aut reiciendis blanditiis animi consequuntur et voluptatem delectus alias.\n\nPossimus excepturi nostrum voluptas deserunt fuga qui a consequuntur a. Veritatis aut quod sapiente et porro cupiditate iusto voluptatibus. Eum rem necessitatibus magni velit harum eos dolorem nostrum id.\n\nDebitis fugit autem quidem repudiandae qui voluptatem incidunt corrupti. Error asperiores similique sapiente totam ipsa. Est quisquam assumenda quod rem maiores aliquam qui. Perspiciatis rerum deleniti ut non qui quod fugit odio et. Quisquam reiciendis et maiores et sit aut nesciunt. İnventore neque aut est omnis quo maiores.",
                            CratedDate = new DateTime(2024, 3, 22, 0, 18, 56, 455, DateTimeKind.Local).AddTicks(6828),
                            CreatedByName = "Jamison Langworth",
                            Date = new DateTime(2024, 4, 17, 8, 20, 28, 998, DateTimeKind.Local).AddTicks(8494),
                            IsActive = true,
                            IsDeleted = true,
                            ModifiedByName = "Easton Nader",
                            ModifiedDate = new DateTime(2024, 11, 25, 1, 36, 10, 949, DateTimeKind.Local).AddTicks(5096),
                            Note = "Voluptatem voluptatum explicabo facere ullam.",
                            SeoAuthor = "Derek Hintz",
                            SeoDescription = "Et perferendis numquam molestiae maxime autem consectetur saepe aperiam ut.",
                            SeoTag = "omnis",
                            Thumbnail = "https://picsum.photos/640/480/?image=920",
                            Title = "At est ut fugit modi.",
                            UserId = 13,
                            ViewsCount = 1505
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 18,
                            CommentCount = 40,
                            Content = "Eveniet dolores itaque eum incidunt modi sed eos. Voluptatem illum harum accusantium eos cum sint aspernatur quas alias. İd reprehenderit distinctio similique nam labore eius vero rerum adipisci. Porro dolorem quia et error eos provident quidem vel. İpsa aut nihil.\n\nSed molestiae deleniti dolorem quidem consectetur possimus et perspiciatis. Saepe dolor voluptatum recusandae impedit esse sint cum quam quia. Commodi expedita blanditiis. Sunt fugit velit vel suscipit cupiditate officia amet. Quo assumenda iusto.\n\nVoluptate itaque velit excepturi iure quia eveniet voluptate. Ullam ut ut inventore unde aperiam. Adipisci quibusdam cupiditate nemo corporis odio quidem voluptatibus eos.",
                            CratedDate = new DateTime(2024, 8, 22, 4, 50, 53, 710, DateTimeKind.Local).AddTicks(9799),
                            CreatedByName = "Heber Bergnaum",
                            Date = new DateTime(2024, 1, 9, 18, 49, 11, 609, DateTimeKind.Local).AddTicks(6039),
                            IsActive = false,
                            IsDeleted = true,
                            ModifiedByName = "Leda Hayes",
                            ModifiedDate = new DateTime(2024, 11, 25, 3, 57, 34, 771, DateTimeKind.Local).AddTicks(8655),
                            Note = "Rerum itaque magni non temporibus.",
                            SeoAuthor = "Florida Becker",
                            SeoDescription = "Quibusdam ut perspiciatis sed nesciunt et magnam vel neque quasi.",
                            SeoTag = "dolor",
                            Thumbnail = "https://picsum.photos/640/480/?image=222",
                            Title = "Voluptatem placeat facere modi consequatur.",
                            UserId = 14,
                            ViewsCount = 6861
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 16,
                            CommentCount = 57,
                            Content = "İste beatae sed sunt id similique blanditiis. Est atque dicta illum consequatur. Facere expedita possimus sunt quasi velit alias aperiam. Repellendus quas non qui eaque commodi labore.\n\nMolestiae consequuntur explicabo officia maxime minus nobis. İmpedit et voluptatum beatae ea dolorem nostrum ratione dolorem fuga. Et eligendi libero adipisci.\n\nSed maiores architecto tempore minima ut voluptas molestiae culpa. Tenetur id et quo vitae. Mollitia sit magni. Et molestias autem repellat quam qui accusamus voluptatem. Reiciendis at enim sit possimus aut sed qui. Omnis qui qui.",
                            CratedDate = new DateTime(2024, 3, 12, 9, 37, 13, 205, DateTimeKind.Local).AddTicks(6822),
                            CreatedByName = "Elva Price",
                            Date = new DateTime(2024, 7, 12, 22, 23, 24, 972, DateTimeKind.Local).AddTicks(5038),
                            IsActive = false,
                            IsDeleted = true,
                            ModifiedByName = "Shirley Heaney",
                            ModifiedDate = new DateTime(2024, 11, 25, 6, 50, 25, 68, DateTimeKind.Local).AddTicks(884),
                            Note = "Et voluptates molestiae rerum earum.",
                            SeoAuthor = "Paige Hilpert",
                            SeoDescription = "Eveniet consequuntur ut voluptate commodi tempore eligendi modi ut voluptatem.",
                            SeoTag = "quo",
                            Thumbnail = "https://picsum.photos/640/480/?image=944",
                            Title = "Culpa fugiat officia voluptas blanditiis.",
                            UserId = 9,
                            ViewsCount = 3795
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            CommentCount = 45,
                            Content = "Praesentium ea eum aut eos qui et consequatur. Molestiae necessitatibus qui. Consequatur qui minima odit rerum id sit qui voluptas. Et accusamus autem recusandae ut vel consequatur.\n\nSint harum repellendus eaque in. Similique esse voluptates saepe. Repellendus reiciendis earum fugiat unde dicta quia omnis. Voluptas aut dicta repellat veritatis incidunt fugit fugiat. Autem dolorem et deserunt quibusdam qui ea mollitia omnis maiores.\n\nDolores sit est saepe aperiam voluptas quae voluptates. Sed quod et deserunt quibusdam eveniet. Beatae est id sequi porro est impedit qui quo. Enim doloribus vel velit iusto odio. Explicabo id sit velit quia molestias expedita a.",
                            CratedDate = new DateTime(2024, 7, 15, 12, 10, 13, 664, DateTimeKind.Local).AddTicks(9576),
                            CreatedByName = "Fiona Vandervort",
                            Date = new DateTime(2024, 1, 20, 4, 38, 24, 31, DateTimeKind.Local).AddTicks(212),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "Clara Von",
                            ModifiedDate = new DateTime(2024, 11, 25, 4, 20, 14, 161, DateTimeKind.Local).AddTicks(5051),
                            Note = "İn sit aliquid non labore.",
                            SeoAuthor = "Armand Wyman",
                            SeoDescription = "Ut fugiat exercitationem fugiat quis quos est quidem sed voluptatibus.",
                            SeoTag = "fugit",
                            Thumbnail = "https://picsum.photos/640/480/?image=202",
                            Title = "Veritatis eius consequatur qui voluptas.",
                            UserId = 5,
                            ViewsCount = 969
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            CommentCount = 69,
                            Content = "Minus aut vitae suscipit quam sed atque officia consectetur. Minus magnam fugit. At omnis possimus quis et. Necessitatibus saepe voluptate. Debitis qui dignissimos. Possimus nihil culpa consequatur enim error sunt.\n\nHarum est laborum iusto voluptatibus officia qui. Et corrupti quos quia. Aperiam et fugiat facere reiciendis. Laboriosam est ex labore.\n\nİpsa ad est distinctio dolores amet. Ducimus nisi eligendi. Quo et nihil ut.",
                            CratedDate = new DateTime(2024, 8, 4, 1, 5, 40, 618, DateTimeKind.Local).AddTicks(239),
                            CreatedByName = "Enid Osinski",
                            Date = new DateTime(2024, 10, 24, 1, 28, 13, 732, DateTimeKind.Local).AddTicks(4791),
                            IsActive = true,
                            IsDeleted = true,
                            ModifiedByName = "Rachael Rowe",
                            ModifiedDate = new DateTime(2024, 11, 25, 8, 7, 23, 959, DateTimeKind.Local).AddTicks(2553),
                            Note = "Veritatis qui et tenetur magni.",
                            SeoAuthor = "Deshaun Cronin",
                            SeoDescription = "Temporibus odit nemo non rerum repellendus doloribus est aut architecto.",
                            SeoTag = "molestiae",
                            Thumbnail = "https://picsum.photos/640/480/?image=81",
                            Title = "Ut esse assumenda ullam possimus.",
                            UserId = 19,
                            ViewsCount = 7505
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 14,
                            CommentCount = 65,
                            Content = "Doloremque sed ratione. Libero iusto quod ut fuga doloribus sunt et aspernatur. Numquam soluta est reprehenderit incidunt veniam eligendi.\n\nVel culpa voluptates omnis eaque voluptas accusantium autem. Repellat optio iure necessitatibus laudantium voluptas. Suscipit amet at. Dolore ipsa id eum voluptas quas ab qui corrupti.\n\nİncidunt fugiat expedita consequatur. Occaecati labore totam excepturi alias dicta qui ex ducimus. Laboriosam earum et ut rerum totam et perspiciatis. Perspiciatis sed fugiat officia tempora sunt. Magni ipsam tempora eum.",
                            CratedDate = new DateTime(2024, 1, 25, 13, 21, 26, 358, DateTimeKind.Local).AddTicks(9331),
                            CreatedByName = "Montana Dickens",
                            Date = new DateTime(2024, 10, 1, 16, 24, 44, 433, DateTimeKind.Local).AddTicks(32),
                            IsActive = false,
                            IsDeleted = true,
                            ModifiedByName = "Reva Orn",
                            ModifiedDate = new DateTime(2024, 11, 25, 7, 23, 5, 891, DateTimeKind.Local).AddTicks(4313),
                            Note = "Repellendus rerum facilis cupiditate omnis.",
                            SeoAuthor = "Winfield Carroll",
                            SeoDescription = "A rerum culpa adipisci sed enim atque dolore repellendus doloribus.",
                            SeoTag = "explicabo",
                            Thumbnail = "https://picsum.photos/640/480/?image=808",
                            Title = "İure laboriosam quis suscipit dolore.",
                            UserId = 18,
                            ViewsCount = 2400
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 9,
                            CommentCount = 74,
                            Content = "Dolor quam consequatur. Totam ut cumque rerum itaque excepturi. Quo minus et occaecati possimus at delectus libero necessitatibus quo. Minima ut laudantium tenetur corporis et assumenda quis. Aut harum similique adipisci at labore nulla illum placeat. Consectetur eligendi rerum eum nemo officia.\n\nTempore esse voluptatem nesciunt. Aut quia deserunt porro minus est adipisci at quod et. Molestiae ipsam et consequuntur ducimus consequuntur totam libero porro. Atque inventore eos aut repellendus id amet consequuntur et ab.\n\nCupiditate ut sed nulla. Tenetur aspernatur ut et molestias fugiat nisi. Magnam voluptatem beatae atque nisi excepturi.",
                            CratedDate = new DateTime(2024, 5, 22, 5, 39, 53, 472, DateTimeKind.Local).AddTicks(3162),
                            CreatedByName = "Silas Huels",
                            Date = new DateTime(2024, 11, 15, 10, 42, 27, 353, DateTimeKind.Local).AddTicks(8171),
                            IsActive = true,
                            IsDeleted = true,
                            ModifiedByName = "Maude Wisozk",
                            ModifiedDate = new DateTime(2024, 11, 25, 7, 35, 16, 710, DateTimeKind.Local).AddTicks(4663),
                            Note = "Rem nisi sed non velit.",
                            SeoAuthor = "Salvatore Kerluke",
                            SeoDescription = "Aut voluptas nisi dolorem rerum quia beatae qui quasi placeat.",
                            SeoTag = "in",
                            Thumbnail = "https://picsum.photos/640/480/?image=976",
                            Title = "Reprehenderit aut mollitia molestiae molestiae.",
                            UserId = 10,
                            ViewsCount = 2478
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 16,
                            CommentCount = 53,
                            Content = "Atque voluptatem dignissimos ab nihil. Reprehenderit nemo facilis enim ut sequi nulla. Esse id consequuntur qui. Reiciendis et modi ut sapiente voluptatem sed. Est quis cupiditate dolorem omnis ratione architecto dolores.\n\nNemo blanditiis nulla non ducimus ipsam voluptas. Aliquam distinctio vel iure sit maiores. Debitis omnis ut eos omnis suscipit.\n\nQuasi maiores earum soluta rerum dolorem quod aut. Molestiae veniam ut amet deserunt animi fugiat debitis occaecati cupiditate. Ducimus iste adipisci sint qui. Nulla voluptas vel rerum. Nihil omnis eligendi iusto animi.",
                            CratedDate = new DateTime(2024, 5, 28, 12, 37, 31, 22, DateTimeKind.Local).AddTicks(7757),
                            CreatedByName = "Elijah Runolfsdottir",
                            Date = new DateTime(2024, 7, 1, 9, 51, 7, 547, DateTimeKind.Local).AddTicks(6782),
                            IsActive = false,
                            IsDeleted = true,
                            ModifiedByName = "Jerrell Ferry",
                            ModifiedDate = new DateTime(2024, 11, 25, 1, 35, 42, 32, DateTimeKind.Local).AddTicks(649),
                            Note = "Sed velit architecto qui sunt.",
                            SeoAuthor = "Emelie Bashirian",
                            SeoDescription = "Dolor incidunt nisi commodi ducimus facere ut perferendis et et.",
                            SeoTag = "eligendi",
                            Thumbnail = "https://picsum.photos/640/480/?image=233",
                            Title = "Voluptates quos quos voluptates accusantium.",
                            UserId = 4,
                            ViewsCount = 1168
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 16,
                            CommentCount = 35,
                            Content = "Blanditiis earum est rerum ipsam nam sit quis autem. İmpedit dolor nam ullam rerum. Eos voluptatem rem quae quis quam repellat voluptatem ut.\n\nDignissimos alias delectus est adipisci quae molestiae beatae asperiores. Non quas aut aliquid itaque voluptatem eos qui. Velit vero alias quam dignissimos placeat.\n\nA aliquam officiis recusandae aut. Neque et sit porro veritatis harum natus qui quod. İpsum enim sit officiis architecto cumque consequatur explicabo vel ea.",
                            CratedDate = new DateTime(2024, 5, 29, 2, 9, 9, 266, DateTimeKind.Local).AddTicks(9730),
                            CreatedByName = "Dayton Hilll",
                            Date = new DateTime(2024, 6, 3, 3, 29, 47, 805, DateTimeKind.Local).AddTicks(589),
                            IsActive = true,
                            IsDeleted = true,
                            ModifiedByName = "Vena Gorczany",
                            ModifiedDate = new DateTime(2024, 11, 25, 15, 37, 29, 296, DateTimeKind.Local).AddTicks(4086),
                            Note = "Non velit harum ipsum dolorem.",
                            SeoAuthor = "Gerard Champlin",
                            SeoDescription = "Numquam id dolorem omnis quis incidunt tenetur vitae magni optio.",
                            SeoTag = "in",
                            Thumbnail = "https://picsum.photos/640/480/?image=197",
                            Title = "Autem et esse molestiae voluptas.",
                            UserId = 12,
                            ViewsCount = 2647
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CommentCount = 83,
                            Content = "Voluptatem voluptatem dolor ad debitis esse veniam omnis voluptatem. Et nesciunt eos quia dolores aut harum ut. Et nisi est labore at nesciunt inventore cum necessitatibus consectetur. Fugiat nihil quo iure quo dicta. Temporibus ut tenetur reprehenderit. Velit beatae molestias eius cupiditate officia voluptates reiciendis quaerat quisquam.\n\nEt earum eligendi perspiciatis nisi necessitatibus velit. Aut et doloremque esse voluptatem enim. Ut quisquam enim ipsa odit quia. Ut sed a ut qui et architecto. Et tenetur et distinctio odit nihil voluptas dolore dolore quibusdam. Soluta perspiciatis asperiores saepe ullam.\n\nQuos dicta ut voluptate reiciendis consequatur sunt. Excepturi exercitationem vel dolor. Nemo alias aut ut veritatis tenetur.",
                            CratedDate = new DateTime(2024, 6, 3, 15, 31, 52, 630, DateTimeKind.Local).AddTicks(6028),
                            CreatedByName = "Lenore Jerde",
                            Date = new DateTime(2024, 1, 29, 15, 12, 26, 106, DateTimeKind.Local).AddTicks(7185),
                            IsActive = false,
                            IsDeleted = true,
                            ModifiedByName = "Deondre Strosin",
                            ModifiedDate = new DateTime(2024, 11, 25, 7, 45, 21, 286, DateTimeKind.Local).AddTicks(4534),
                            Note = "Maxime repellat cumque omnis odit.",
                            SeoAuthor = "Avis Kilback",
                            SeoDescription = "Porro sint in minima veniam eum optio et dolores atque.",
                            SeoTag = "harum",
                            Thumbnail = "https://picsum.photos/640/480/?image=746",
                            Title = "Eum cumque perferendis est ut.",
                            UserId = 17,
                            ViewsCount = 7650
                        });
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CratedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CratedDate = new DateTime(2024, 2, 16, 23, 58, 10, 546, DateTimeKind.Local).AddTicks(5764),
                            CreatedByName = "Fausto Tillman",
                            Description = "Magni et porro quis et rerum et nobis et nemo.",
                            IsActive = false,
                            IsDeleted = true,
                            ModifiedByName = "Osbaldo Stanton",
                            ModifiedDate = new DateTime(2024, 11, 25, 17, 27, 49, 436, DateTimeKind.Local).AddTicks(1851),
                            Name = "Automotive",
                            Note = "Sit voluptatum quis consectetur ut."
                        },
                        new
                        {
                            Id = 2,
                            CratedDate = new DateTime(2023, 11, 27, 15, 9, 26, 84, DateTimeKind.Local).AddTicks(3294),
                            CreatedByName = "Diego Jerde",
                            Description = "Porro quia nesciunt cumque perferendis expedita occaecati unde doloremque sint.",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Sim Bernier",
                            ModifiedDate = new DateTime(2024, 11, 25, 22, 20, 5, 348, DateTimeKind.Local).AddTicks(2522),
                            Name = "Industrial",
                            Note = "Accusantium soluta maxime enim omnis."
                        },
                        new
                        {
                            Id = 3,
                            CratedDate = new DateTime(2024, 10, 2, 19, 16, 28, 766, DateTimeKind.Local).AddTicks(6137),
                            CreatedByName = "Karlee McClure",
                            Description = "Minus numquam facere sed fuga et autem aut voluptas aut.",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Penelope Cartwright",
                            ModifiedDate = new DateTime(2024, 11, 25, 6, 45, 39, 767, DateTimeKind.Local).AddTicks(4629),
                            Name = "Industrial",
                            Note = "Voluptatem laborum id eius odio."
                        },
                        new
                        {
                            Id = 4,
                            CratedDate = new DateTime(2024, 6, 30, 10, 36, 54, 51, DateTimeKind.Local).AddTicks(9429),
                            CreatedByName = "Leonard Wiegand",
                            Description = "Et consequatur quaerat cupiditate rem facere maiores repellat omnis beatae.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "Lester Kutch",
                            ModifiedDate = new DateTime(2024, 11, 25, 18, 13, 5, 327, DateTimeKind.Local).AddTicks(3505),
                            Name = "Health",
                            Note = "Asperiores non sit corrupti quo."
                        },
                        new
                        {
                            Id = 5,
                            CratedDate = new DateTime(2024, 9, 10, 4, 41, 42, 230, DateTimeKind.Local).AddTicks(3497),
                            CreatedByName = "Urban Fritsch",
                            Description = "Quia non consequatur error voluptates rem aut maxime velit molestias.",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Mathilde Daniel",
                            ModifiedDate = new DateTime(2024, 11, 25, 13, 49, 56, 205, DateTimeKind.Local).AddTicks(1562),
                            Name = "Music",
                            Note = "Non explicabo quis magnam placeat."
                        },
                        new
                        {
                            Id = 6,
                            CratedDate = new DateTime(2024, 5, 19, 3, 39, 32, 217, DateTimeKind.Local).AddTicks(2866),
                            CreatedByName = "Nadia Beahan",
                            Description = "Et eligendi nulla neque ea ad harum culpa impedit modi.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "Manuel Smith",
                            ModifiedDate = new DateTime(2024, 11, 25, 22, 14, 55, 503, DateTimeKind.Local).AddTicks(9135),
                            Name = "Tools",
                            Note = "Ad explicabo quo eaque enim."
                        },
                        new
                        {
                            Id = 7,
                            CratedDate = new DateTime(2024, 6, 19, 22, 34, 44, 964, DateTimeKind.Local).AddTicks(8207),
                            CreatedByName = "Vanessa Wilderman",
                            Description = "Modi provident commodi excepturi iusto officiis molestias saepe alias placeat.",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Kian Donnelly",
                            ModifiedDate = new DateTime(2024, 11, 25, 0, 11, 12, 870, DateTimeKind.Local).AddTicks(352),
                            Name = "Beauty",
                            Note = "Assumenda cum non distinctio est."
                        },
                        new
                        {
                            Id = 8,
                            CratedDate = new DateTime(2024, 8, 19, 19, 27, 10, 110, DateTimeKind.Local).AddTicks(6952),
                            CreatedByName = "Brendon Bashirian",
                            Description = "Ad sit quisquam adipisci sit repellendus molestiae delectus porro fugiat.",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Petra Paucek",
                            ModifiedDate = new DateTime(2024, 11, 25, 20, 12, 12, 590, DateTimeKind.Local).AddTicks(3900),
                            Name = "Electronics",
                            Note = "Blanditiis quia consectetur voluptas dolorem."
                        },
                        new
                        {
                            Id = 9,
                            CratedDate = new DateTime(2024, 10, 3, 8, 25, 14, 48, DateTimeKind.Local).AddTicks(6151),
                            CreatedByName = "Evie Wiza",
                            Description = "Quod eaque vel id est eos eligendi voluptas incidunt voluptatem.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "Pattie Stroman",
                            ModifiedDate = new DateTime(2024, 11, 24, 23, 1, 18, 80, DateTimeKind.Local).AddTicks(5076),
                            Name = "Industrial",
                            Note = "Repellendus fugiat soluta necessitatibus est."
                        },
                        new
                        {
                            Id = 10,
                            CratedDate = new DateTime(2024, 10, 11, 5, 0, 43, 31, DateTimeKind.Local).AddTicks(337),
                            CreatedByName = "Jarret Maggio",
                            Description = "Ut ut voluptatum aliquam nisi beatae earum quisquam rerum dicta.",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Jadyn Stehr",
                            ModifiedDate = new DateTime(2024, 11, 25, 21, 6, 5, 140, DateTimeKind.Local).AddTicks(283),
                            Name = "Baby",
                            Note = "Vel vero consequuntur et qui."
                        },
                        new
                        {
                            Id = 11,
                            CratedDate = new DateTime(2024, 10, 4, 10, 4, 57, 669, DateTimeKind.Local).AddTicks(4063),
                            CreatedByName = "Rowan Ritchie",
                            Description = "Consequuntur velit quia adipisci doloremque incidunt reiciendis est quisquam est.",
                            IsActive = true,
                            IsDeleted = true,
                            ModifiedByName = "Kennith Farrell",
                            ModifiedDate = new DateTime(2024, 11, 25, 16, 32, 38, 763, DateTimeKind.Local).AddTicks(4812),
                            Name = "Grocery",
                            Note = "Repellendus animi vel a quia."
                        },
                        new
                        {
                            Id = 12,
                            CratedDate = new DateTime(2024, 7, 15, 16, 33, 59, 653, DateTimeKind.Local).AddTicks(1494),
                            CreatedByName = "Claudine Pollich",
                            Description = "Enim voluptatibus est amet et quam hic voluptas voluptatem ducimus.",
                            IsActive = true,
                            IsDeleted = true,
                            ModifiedByName = "Jeremy Metz",
                            ModifiedDate = new DateTime(2024, 11, 25, 22, 29, 21, 790, DateTimeKind.Local).AddTicks(9726),
                            Name = "Sports",
                            Note = "Nostrum voluptatem dolores enim saepe."
                        },
                        new
                        {
                            Id = 13,
                            CratedDate = new DateTime(2024, 11, 13, 22, 22, 21, 531, DateTimeKind.Local).AddTicks(166),
                            CreatedByName = "Phyllis Howe",
                            Description = "Aut non sit illo eum inventore quia provident explicabo sint.",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Shawna Bahringer",
                            ModifiedDate = new DateTime(2024, 11, 25, 11, 10, 13, 347, DateTimeKind.Local).AddTicks(5425),
                            Name = "Outdoors",
                            Note = "Nihil voluptatem nesciunt consequatur minima."
                        },
                        new
                        {
                            Id = 14,
                            CratedDate = new DateTime(2024, 2, 2, 2, 35, 49, 225, DateTimeKind.Local).AddTicks(9457),
                            CreatedByName = "Elva Brakus",
                            Description = "Optio molestiae at delectus veritatis id autem dicta corporis consequuntur.",
                            IsActive = true,
                            IsDeleted = true,
                            ModifiedByName = "Sally Blick",
                            ModifiedDate = new DateTime(2024, 11, 25, 15, 50, 10, 393, DateTimeKind.Local).AddTicks(806),
                            Name = "Toys",
                            Note = "Rerum velit voluptas dignissimos quis."
                        },
                        new
                        {
                            Id = 15,
                            CratedDate = new DateTime(2024, 10, 30, 20, 24, 26, 131, DateTimeKind.Local).AddTicks(2079),
                            CreatedByName = "Chaim Swaniawski",
                            Description = "Ut consequatur aperiam fugit autem mollitia distinctio reprehenderit consequatur vitae.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "Marlon Schuppe",
                            ModifiedDate = new DateTime(2024, 11, 25, 9, 48, 52, 246, DateTimeKind.Local).AddTicks(7759),
                            Name = "Computers",
                            Note = "Aspernatur impedit possimus dicta cupiditate."
                        },
                        new
                        {
                            Id = 16,
                            CratedDate = new DateTime(2024, 2, 7, 18, 15, 38, 46, DateTimeKind.Local).AddTicks(3911),
                            CreatedByName = "Madie Bogan",
                            Description = "Nemo a non minima eum occaecati fugiat qui odio dolor.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "Mazie Bosco",
                            ModifiedDate = new DateTime(2024, 11, 25, 7, 5, 5, 81, DateTimeKind.Local).AddTicks(1080),
                            Name = "Computers",
                            Note = "Voluptas ab dolorum quae et."
                        },
                        new
                        {
                            Id = 17,
                            CratedDate = new DateTime(2024, 3, 3, 10, 14, 3, 747, DateTimeKind.Local).AddTicks(8293),
                            CreatedByName = "Caden Shanahan",
                            Description = "Quis similique optio hic exercitationem assumenda inventore natus deleniti excepturi.",
                            IsActive = false,
                            IsDeleted = true,
                            ModifiedByName = "Simeon Heidenreich",
                            ModifiedDate = new DateTime(2024, 11, 25, 14, 28, 23, 283, DateTimeKind.Local).AddTicks(6786),
                            Name = "Toys",
                            Note = "Et quasi voluptatibus dolor laudantium."
                        },
                        new
                        {
                            Id = 18,
                            CratedDate = new DateTime(2024, 5, 7, 8, 38, 33, 290, DateTimeKind.Local).AddTicks(5691),
                            CreatedByName = "Bernardo Grant",
                            Description = "Blanditiis error molestiae omnis et voluptas molestiae fugiat itaque minus.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "Albertha Breitenberg",
                            ModifiedDate = new DateTime(2024, 11, 25, 4, 53, 49, 61, DateTimeKind.Local).AddTicks(1663),
                            Name = "Computers",
                            Note = "Ducimus libero iure ipsa adipisci."
                        },
                        new
                        {
                            Id = 19,
                            CratedDate = new DateTime(2024, 11, 5, 2, 44, 8, 737, DateTimeKind.Local).AddTicks(685),
                            CreatedByName = "Celine Mueller",
                            Description = "Est voluptatibus nulla praesentium in laudantium et et optio rerum.",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Kirstin Kiehn",
                            ModifiedDate = new DateTime(2024, 11, 25, 20, 21, 27, 46, DateTimeKind.Local).AddTicks(7796),
                            Name = "Kids",
                            Note = "Officia voluptates qui aut mollitia."
                        },
                        new
                        {
                            Id = 20,
                            CratedDate = new DateTime(2024, 9, 26, 8, 41, 52, 42, DateTimeKind.Local).AddTicks(3291),
                            CreatedByName = "Ruthe Bruen",
                            Description = "Non temporibus iure ipsa nulla sit placeat sit et doloribus.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "Adolfo Schneider",
                            ModifiedDate = new DateTime(2024, 11, 25, 17, 51, 10, 122, DateTimeKind.Local).AddTicks(148),
                            Name = "Music",
                            Note = "Enim vitae dignissimos odit animi."
                        });
                });

            modelBuilder.Entity("Entities.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CratedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CratedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CratedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("Picture")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Article", b =>
                {
                    b.HasOne("Entities.Models.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("Articles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.Comment", b =>
                {
                    b.HasOne("Entities.Models.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.HasOne("Entities.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Entities.Models.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Entities.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
